name: Test macos13-arm64

on: #[push]
  workflow_dispatch:
  
jobs:
  test-run:
    runs-on: macos-14-large
    steps:
      - name: test install simulators
        run: |
          sudo xcode-select --switch "/Applications/Xcode_16.0.app" 
          sudo /Applications/Xcode_16.0.app/Contents/Developer/usr/bin/xcodebuild -downloadAllPlatforms
