name: another test

on: 
  workflow_dispatch
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-13-xlarge, macos-14-large, macos-13, macos-15, macos-15-large, macos-15-xlarge ]     
    runs-on: ${{ matrix.os }}
    steps:
      - name: cinstall ninja
        shell: bash
        run: |
          brew install ninja
      - name: run ninja
        shell: bash
        run: |
          ninja --version
          echo 'cmake_minimum_required(VERSION 3.10)' >> CMakeLists.txt
          echo 'project(NinjaTest NONE)' >> CMakeLists.txt
          cmake -GNinja .
