on: 
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ayupov-slim-ubunta20, ayupov-slim-ubunta22]
      fail-fast: false  
    runs-on: ${{ matrix.os }}
    name: test var
    steps:
      - name: test package installation
        shell: bash
        run: |
            npm install -g @bazel/bazelisk

            # run bazelisk once in order to instal /usr/local/bin/bazel binary
            sudo -u $SUDO_USER bazel version

            bazel --version
            bazelisk --version
