on: 
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ayupov-slim-ubunta20, ayupov-slim-ubunta22]
      fail-fast: false  
    runs-on: ${{ matrix.os }}
    name: test var
    steps:
      - name: test package installation
        shell: bash
        run: |
            sudo du -sh /opt/pipx_bin
            package="ansible-core"
            pipx install $package
            pipx inject $package ansible
            sudo du -sh /opt/pipx_bin
            package="yamllint"
            pipx install $package
            sudo du -sh /opt/pipx_bin

