on: 
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ayupov-slim-ubunta20, ayupov-slim-ubunta22]
      fail-fast: false  
    runs-on: ${{ matrix.os }}
    name: test var
    steps:
      - name: test package installation
        shell: bash
        run: |
            curl https://github.com/sbt/sbt/releases/download/v1.9.6/sbt-1.9.6.tgz -4 -sL -o '/tmp/sbt.tgz' -w '%{http_code}'
            tar zxf /tmp/sbt.tgz -C /usr/share
            ln -s /usr/share/sbt/bin/sbt /usr/bin/sbt
            echo "run sbt"
            sbt --version

