on: 
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ayupov-slim-ubunta20, ayupov-slim-ubunta22]
      fail-fast: false  
    runs-on: ${{ matrix.os }}
    name: test var
    steps:
      - name: test package installation
        shell: bash
        run: |
            sudo du -sh /usr/local/bin/* | sort -h
            echo "------------"
            sudo du -sh /var/lib/docker/overlay2/
            echo "------------"
            sudo du -sh /var/lib/docker/overlay2/* | sort -h
