on: 
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ayupov-slim-ubunta20, ayupov-slim-ubunta22]
      fail-fast: false  
    runs-on: ${{ matrix.os }}
    name: test var
    steps:
      - name: test package installation
        shell: bash
        run: |
            apt-get install -y chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev
            PHANTOM_JS=phantomjs-2.1.1-linux-x86_64
            curl https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2 -4 -sL -o '/tmp/phantomjs-2.1.1-linux-x86_64.tar.bz2' -w '%{http_code}'
            tar xjf /tmp/$PHANTOM_JS.tar.bz2 -C /usr/local/share
            ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin

