on: 
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ayupov-slim-ubunta20, ayupov-slim-ubunta22]
      fail-fast: false  
    runs-on: ${{ matrix.os }}
    name: test var
    steps:
      - name: test package installation
        shell: bash
        run: |
            curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz -4 -sL -o '/tmp/oc.tar.gz' -w '%{http_code}'

            tar xzf /tmp/oc.tar.gz -C /usr/local/bin oc
            oc version

