on: 
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ayupov-slim-ubunta20, ayupov-slim-ubunta22]
      fail-fast: false  
    runs-on: ${{ matrix.os }}
    name: test var
    steps:
      - name: test package installation
        shell: bash
        run: |
            echo "deb https://cli-assets.heroku.com/channels/stable/apt ./" > /etc/apt/sources.list.d/heroku.list
            
            # install heroku's release key for package verification
            curl https://cli-assets.heroku.com/channels/stable/apt/release.key | apt-key add -
            
            # install heroku
            apt-get update -y && apt-get install -y heroku

