on: 
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ayupov-slim-ubunta20, ayupov-slim-ubunta22]
      fail-fast: false  
    runs-on: ${{ matrix.os }}
    name: test var
    steps:
      - name: test package installation
        shell: bash
        run: |
            curl https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz -4 -sL -o '/tmp/oras_1.1.0_linux_amd64.tar.gz' -w '%{http_code}'

            tar xzf /tmp/oras_1.1.0_linux_amd64.tar.gz -C /usr/local/bin oras
            

